### ISSUE TITLE
Fix the "Get Involved" section and Footer

### ISSUE THREAD

**Issue by aabowen** [cmxslack/cmxslack.github.io#1]
Not sure why the "Get Involved" section is not working, nor is the footer. #Hacktoberfest

**Comment by phoebeclarke** [comment]
I can look into this :)

**Comment by sschadwick** [comment]
Looks like /_includes/getinvolved.html is commented out

**Comment by LukeSchlangen** [comment]
I uncommented and formatted that file from sschadwick's suggestion. It doesn't resolve the footer issue though.

**Comment by LukeSchlangen** [comment]
It looks like the "location" section isn't working because the properties haven't been added to the yml file like they have for social. If you look at how social is included in here, there isn't that same information for location: https://github.com/cmxslack/cmxslack.github.io/blob/master/_config.yml

I don't know your address, so I can't add it for you, but it would look something like it does for social:
```
  - title: slack
    url: http://communitymanagerscmx.slack.com
  - title: github
    url: http://github.com/cmxslack/
  - title: twitter
    url: https://twitter.com/cmx
```

It seems like this may have been based on a template, I would recommend going back to that template and seeing what they have in the .yml file for location.

Good luck!

**Comment by aabowen** [comment]
Yeah, I don't want the location section anymore - I want it removed and updated with Code of Conduct and social - that's it.

**Comment by aabowen** [comment]
Luke, I merged your PR #2 - I just refreshed and the "Get Involved" bit is still not showing up.

**Comment by LukeSchlangen** [comment]
Hi @aabowen I'm not super familiar with rails, so I'm not sure where to go with this. It seems like the section is not being imported correctly when I get to the chrome developer tools, so the code isn't being adding to the page, but I don't fully understand how rails is doing that (or in this case, not doing that).

**Comment by sschadwick** [comment]
@LukeSchlangen I believe this is a Jekyll project, so no knowledge of Ruby/Rails is required.

I don't have time to dig too deep into this right now, but I would suggest using Jekyll to build a local copy, and debugging from there. Something with the project is breaking during the build process and thus not incorporating that section. Github is automagically re-building and hosting the project with every new commit.

**Comment by phoebeclarke** [comment]
I've removed the location section from footer.html and replaced it with Code of Conduct as @aabowen asked.
In terms of adding new sections like location: you write the content in config.yml, and organise the layout in footer.html.

**Comment by aabowen** [comment]
Thank you @phoebeclarke !
